# 🔹 Risk Management Configurations (from strategy perspective)
risk:
  max_drawdown: 5.0
  daily_loss_limit: 2.0
  volatility_threshold: 35.0

# 🔹 Execution Strategy
execution:
  slippage_tolerance: 0.001
  latency_budget_ms: 50
  retry_attempts: 3

# 🔹 Strategies Enabled
strategies:
  enabled:
    - TrendFollowing
    - MeanReversion

# 🔹 Trading Mode Configurations
trading_mode:
  live_trading: false
  testnet: true
