# 🔹 Trading Mode: "testing" (Backtest) or "live" (Real Market Execution)
mode: "testing"

# 🔹 Market Data & WebSocket Configuration
websocket:
  enable_real_time_data: true
  polygon_key: 'your_polygon_api_key'
  symbols: ['BTCUSD', 'ETHUSD', 'AAPL', 'TSLA']

# 🔹 Market Data Fetching Interval (in seconds)
data_feed_interval: 1  

# 🔹 Risk Management Configuration
risk:
  max_drawdown: 0.1  # Stop trading if equity drops 10%
  risk_threshold: 0.02  # Risk per trade
  stop_loss: 0.015
  take_profit: 0.03
  position_sizing_strategy: "adaptive"  # Options: fixed, adaptive, ai_dynamic

# 🔹 Execution Engine Settings
execution:
  slippage_protection: true
  smart_order_routing: true
  trade_confirmation_required: false  
  slippage_tolerance: 0.001
  latency_budget_ms: 50

# 🔹 Broker API Keys
broker_api_keys:
  zerodha: 'your_zerodha_api_key'
  binance: 'your_binance_api_key'

# 🔹 Database & Storage Configuration
database:
  path: 'storage/trade_history.db'
  backup_frequency: "daily"  
  log_trades: true  

# 🔹 Logging & Debugging Settings
logging:
  level: "INFO"  
  log_to_file: true
  log_file_path: "logs/bot_activity.log"

# 🔹 AI Model Settings
ai_trading:
  enable_live_adaptation: true  
  strategy_selection: "reinforcement_learning"  
  model_path: "models/trading_ai_model.pth"

# 🔹 Backtesting Settings
backtesting:
  historical_data_path: "data/historical/"
  start_date: "2015-01-01"
  end_date: "2024-01-01"
  capital: 100000  
  commission: 0.0005  

# 🔹 Notifications & Alerts
notifications:
  enable_alerts: true
  email_alerts: false
  telegram_alerts: true
  telegram_api_key: "your_telegram_api_key"
  telegram_chat_id: "your_telegram_chat_id"

# 🔹 Strategies Configuration
strategies:
  Stocks: "mean_reversion"
  Forex: "momentum_breakout"
  Crypto: "volatility_scalping"
  Commodities: "fundamental_trend_following"
  Indices: "macroeconomic_trend"

# 🔹 Technical indicators per asset type
indicators:
  Stocks: ["RSI", "MACD", "BollingerBands"]
  Forex: ["MovingAverages", "FibonacciRetracements"]
  Crypto: ["VWAP", "OrderFlowAnalysis"]
  Commodities: ["SupplyDemandAnalysis", "Seasonality"]
  Indices: ["VolatilityIndex", "GDPCorrelation"]

# 🔹 Fundamental analysis sources per asset type
fundamental_sources:
  Stocks: ["EarningsReports", "SECFilings"]
  Forex: ["InterestRates", "GDPReports"]
  Crypto: ["OnChainAnalysis", "MarketSentiment"]
  Commodities: ["OilProductionData", "WeatherReports"]
  Indices: ["BondYields", "CPIReports"]

# 🔹 Sentiment Analysis Configuration
sentiment:
  window_size: 15
  weights:
    news: 0.6
    social: 0.4
  news_sources: ["newsapi", "finnhub"]
  api_keys:
    newsapi: ${NEWSAPI_KEY}
    finnhub: ${FINNHUB_KEY}
  hf_token: ${HF_TOKEN}
