# 🔹 Trading Mode: "testing" (Backtest) or "live" (Real Market Execution)
mode: "testing"

# 🔹 Market Data & WebSocket Configuration
websocket:
  enable_real_time_data: true
  polygon_key: 'your_polygon_api_key'
  symbols: ['BTCUSD', 'ETHUSD', 'AAPL', 'TSLA']

# 🔹 Market Data Fetching Interval (in seconds)
data_feed_interval: 1  

# 🔹 Risk Management Configuration
risk:
  max_drawdown: 0.1  # Stop trading if equity drops 10%
  risk_threshold: 0.02  # Risk per trade
  stop_loss: 0.015
  take_profit: 0.03
  position_sizing_strategy: "adaptive"  # Options: fixed, adaptive, ai_dynamic

# 🔹 Execution Engine Settings
execution:
  slippage_protection: true
  smart_order_routing: true
  trade_confirmation_required: false  
  slippage_tolerance: 0.001
  latency_budget_ms: 50

# 🔹 Broker API Keys
broker_api_keys:
  zerodha: 'your_zerodha_api_key'
  binance: 'your_binance_api_key'

# 🔹 Database & Storage Configuration
database:
  path: 'storage/trade_history.db'
  backup_frequency: "daily"  
  log_trades: true  

# 🔹 Logging & Debugging Settings
logging:
  level: "INFO"  

# 🔹 Conflict Resolution Configuration
conflict_resolution:
  # Weight management
  bias_threshold: 1.5
  bias_correction_factor: 1.3
  max_confidence_ratio: 1.8
  
  # Drift detection
  drift_threshold: 0.15
  max_drift_models: 2
  
  # RL integration
  rl_confidence_threshold: 0.78
  rl_min_samples: 50
  
  # Regime weights
  regime_weights:
    trending:
      technical: 0.6
      fundamental: 0.2
      sentiment: 0.2
    volatile:
      rl: 0.5
      correlation: 0.3
      technical: 0.2
  default_weights:
    technical: 0.3
    fundamental: 0.25
    sentiment: 0.2
    rl: 0.15
    correlation: 0.1
  log_to_file: true
  log_file_path: "logs/bot_activity.log"

# 🔹 AI Model Settings
ai_trading:
  enable_live_adaptation: true  
  strategy_selection: "reinforcement_learning"  
  model_path: "models/trading_ai_model.pth"

# 🔹 Backtesting Settings
backtesting:
  historical_data_path: "data/historical/"
  start_date: "2015-01-01"
  end_date: "2024-01-01"
  capital: 100000  
  commission: 0.0005  

# 🔹 Notifications & Alerts
notifications:
  enable_alerts: true
  email_alerts: false
  telegram_alerts: true
  telegram_api_key: "your_telegram_api_key"
  telegram_chat_id: "your_telegram_chat_id"

# 🔹 Strategies Configuration
strategies:
  Stocks: "mean_reversion"
  Forex: "momentum_breakout"
  Crypto: "volatility_scalping"
  Commodities: "fundamental_trend_following"
  Indices: "macroeconomic_trend"

# 🔹 Technical indicators per asset type
indicators:
  Stocks: ["RSI", "MACD", "BollingerBands"]
  Forex: ["MovingAverages", "FibonacciRetracements"]
  Crypto: ["VWAP", "OrderFlowAnalysis"]
  Commodities: ["SupplyDemandAnalysis", "Seasonality"]
  Indices: ["VolatilityIndex", "GDPCorrelation"]

# 🔹 Fundamental analysis sources per asset type
fundamental_sources:
  Stocks: ["EarningsReports", "SECFilings"]
  Forex: ["InterestRates", "GDPReports"]
  Crypto: ["OnChainAnalysis", "MarketSentiment"]
  Commodities: ["OilProductionData", "WeatherReports"]
  Indices: ["BondYields", "CPIReports"]

# 🔹 Sentiment Analysis Configuration
sentiment:
  window_size: 15
  weights:
    news: 0.6
    social: 0.4
  news_sources: ["newsapi", "finnhub"]
  api_keys:
    newsapi: ${NEWSAPI_KEY}
    finnhub: ${FINNHUB_KEY}
  hf_token: ${HF_TOKEN}

# 🔹 Meta Trading Configuration
meta_trading:
  base_weights:
    trending:
      technical: 0.6
      fundamental: 0.2
      sentiment: 0.1
      rl: 0.0
      correlation: 0.1
    volatile:
      technical: 0.3
      fundamental: 0.1
      sentiment: 0.2
      rl: 0.4
      correlation: 0.0
  volatility_threshold: 0.35

# 🔹 Ensemble Voting Configuration
ensemble_voting:
  training_window: 252  # 1 year of trading days
  retraining_interval: 7  # days
  volatility_thresholds:
    low: 0.2
    medium: 0.4
    high: 0.6
  asset_weights:
    stocks:
      fundamental: 0.4
      technical: 0.3
    forex:
      technical: 0.6
      sentiment: 0.2
    crypto:
      sentiment: 0.5
      correlation: 0.3

# 🔹 Transformer LSTM Configuration
transformer_lstm:
  input_size: 128
  lstm_hidden: 64
  lstm_layers: 2
  n_heads: 8
  ff_dim: 256
  transformer_layers: 3
  output_size: 64
  short_term_dim: 32
  max_variance: 0.25
  retrain_threshold: 1000
  regime_types: ['trending', 'volatile', 'mean_reverting', 'neutral']
  model_weights: '/models/transformer_lstm.pt'

# 🔹 Conflict Resolution Configuration
conflict_resolution:
  bias_threshold: 0.4
  drift_threshold: 0.15
  max_drift_models: 2
  default_weights:
    technical: 0.3
    fundamental: 0.25
    sentiment: 0.2
    rl: 0.15
    correlation: 0.1
  regime_weights:
    trending:
      technical: 0.5
      fundamental: 0.2
      sentiment: 0.3
    volatile:
      rl: 0.4
      technical: 0.3
      correlation: 0.3
    mean_reverting:
      fundamental: 0.4
      technical: 0.4

# 🔹 Report Format Configuration      
formats:
  default: html
  available: [json, pdf, md, html, dashboard]

# 🔹 Report Schedule Configuration
schedule:
  daily: "08:00"
  weekly: "Monday 08:00"

# 🔹 Email Configuration  
email:
  enabled: false
  recipients: []
